javac boy.java
javac miser_boy.java
javac generous_boy.java
javac geeks_boy.java
javac girl.java
javac choosy_girl.java
javac normal_girl.java
javac desperate_girl.java
javac gift.java
javac luxury_gift.java
javac utility_gift.java
javac couple.java
javac write_boys3.java
javac write_girls3.java
javac write_file3.java
javac ques3_algo.java
javac ques9_algo.java
javac main9.java
java main9
cat boys3.csv
cat girls3.csv
cat event3.csv